In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [ ]:
homepricestown = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Csv_file/homepricestown.csv')
homepricestown.keys()
print(homepricestown)

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000


In [ ]:
dummies = pd.get_dummies(homepricestown['town'])
mergerd = pd.concat([homepricestown, dummies], axis='columns')

In [ ]:
finalDf = mergerd.drop(columns= ['town', 'monroe township'])
townPriceDf = pd.DataFrame(finalDf)
print(townPriceDf)

    area   price  robinsville  west windsor
0   2600  550000        False         False
1   3000  565000        False         False
2   3200  610000        False         False
3   3600  680000        False         False
4   4000  725000        False         False
5   2600  585000        False          True
6   2800  615000        False          True
7   3300  650000        False          True
8   3600  710000        False          True
9   2600  575000         True         False
10  2900  600000         True         False
11  3100  620000         True         False
12  3600  695000         True         False


In [ ]:
model = linear_model.LinearRegression()

In [ ]:
X = townPriceDf.drop(columns= ['price'])
Y = townPriceDf['price']

model.fit(X, Y)

LinearRegression()

In [ ]:
model.predict(pd.DataFrame({
    'area': [2800, 3400, 3800],
    'robinsville': [1, 0, 0],
    'west windsor': [0, 1, 0]
}))

array([590775.63964739, 681241.6684584 , 691986.66953343])

In [ ]:
model.score(X, Y)

0.9573929037221871

In [ ]:
X = homepricestown.drop(columns= ['price'])
Y = homepricestown['price']

In [ ]:
preprocessor = ColumnTransformer(
    transformers= [('encoded', OneHotEncoder(drop='first', sparse_output=False), ['town'])
    ],
    remainder='passthrough',
    force_int_remainder_cols=False
)

pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', linear_model.LinearRegression())
])

pipeline.fit(X,Y)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('encoded',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['town'])])),
                ('model', LinearRegression())])

In [ ]:
pipeline.predict(pd.DataFrame({
    'town': ['west windsor', 'robinsville'],
    'area': [3400, 2800]
}))

array([681241.6684584 , 590775.63964739])

In [ ]:
pipeline.score(X, Y)

0.9573929037221873

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
carPrices = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Csv_file/carprices.csv')
carPrices.keys()
print(carPrices)

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5


In [ ]:
X = carPrices.drop(columns= ['Sell Price($)'])
Y = carPrices['Sell Price($)']

In [ ]:
process = ColumnTransformer(
    transformers=[
        ('car', OneHotEncoder(drop= 'first', sparse_output = False), ['Car Model'])
    ],
    remainder='passthrough'
)
pl = Pipeline([
    ('processing', process),
    ('model', linear_model.LinearRegression())
])

pl.fit(X, Y)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('processing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('car',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Car Model'])])),
                ('model', LinearRegression())])

In [ ]:
pl.predict(pd.DataFrame({
    'Car Model': ['BMW X5', 'Mercedez Benz C class', 'BMW X5'],
    'Mileage': [10000,  45000, 86000],
    'Age(yrs)': [6, 4, 7]
}))

array([40542.47593333, 36991.31721062, 11080.74313219])

In [ ]:
pl.score(X, Y)

0.9417050937281082